version: "3"

services:
    postgres:
        image: postgres
        ports:
            - 5432:5432
        network_mode: host
        environment:
            - POSTGRES_PASSWORD="my-postgres-pass"

    jwthenticator:
        image: clarotyltd/jwthenticator
        ports:
            - 8080:8080
        network_mode: host
        environment:
            - DB_PASS="my-postgres-pass"
        depends_on:
            - postgres
